Web Portfolio Mobile Version
Loltolo-Lesapiti/Web-Mobile pull request #1
Opened 2022-04-29 19:15 UTC by Loltolo-Lesapiti

This is a personal portfolio page design for mobile.

2022-04-29 21:37 UTC, koomekevo requested changes
Hi @Loltolo-Lesapiti, 

<img src="https://media0.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
:heavy_check_mark: Your project has no linter errors.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-29 21:37 UTC, koomekevo commented on index.html
> +                <h3>CANOPY</h3>
@Loltolo-Lesapiti Kindly align the left padding as shown in the below screenshot

 ![lesapititoniccorrect](https://user-images.githubusercontent.com/87413774/166071228-34094f31-55b8-4274-80cb-20242a9acf74.png) 

The below screenshot is your design

 ![lesapititonicwrongedited](https://user-images.githubusercontent.com/87413774/166071745-787c26f1-d2a9-498a-b984-9ea959fac8b1.png)

2022-04-29 21:37 UTC, koomekevo commented on README.md
> -# Project Name
@Loltolo-Lesapiti Kindly give your project name a descriptive name.

2022-04-30 00:40 UTC, Loltolo-Lesapiti commented on README.md
> -# Project Name
@koomekevo please check now. I made the changes.

2022-04-30 01:09 UTC, smunozmo approved these changes
Hi @Loltolo-Lesapiti, 👋 

## Highlights 👏 

- Great work using the right GitHub Flow.
- Your README looks professional, well done!
- Commits are descriptive, good work.
- Linters are working properly, great job!

Your project is complete!  There is nothing else to say other than... it's time to merge it! 🚀 
Very nice work, congratulations! 🎉 

### APPROVED! 💯  💯  💯 

<img src="https://media4.giphy.com/media/cFkiFMDg3iFoI/giphy.gif"/>


Cheers and Happy coding! 🤓 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-30 01:09 UTC, smunozmo commented on index.html
> +        </ul>
[OPTIONAL] Something happened to the languages list, it would be better to fix it in order to display it as the Figma template:

Your design:
![Captura de pantalla 2022-04-29 a la(s) 8 06 24 p  m](https://user-images.githubusercontent.com/83717285/166084623-01f40b48-f31f-4def-8a33-84fa5f908be0.png)

2022-04-30 17:52 UTC, merged